package ru.gt2.gar.db.tm;

import com.google.common.collect.ImmutableMap;
import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.CodeBlock;
import com.palantir.javapoet.FieldSpec;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.ParameterizedTypeName;
import com.palantir.javapoet.TypeName;
import com.palantir.javapoet.TypeSpec;
import com.palantir.javapoet.WildcardTypeName;
import lombok.RequiredArgsConstructor;
import ru.gt2.gar.db.NamingStrategy;
import ru.gt2.gar.db.schema.DatabaseSchema;
import ru.gt2.gar.db.sql.QueriesGenerator;
import ru.gt2.gar.domain.GarType;

import javax.lang.model.element.Modifier;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;

import static java.util.stream.Collectors.joining;

@RequiredArgsConstructor
public class TableMappingGenerator {
    private static final ClassName ABSTRACT_TABLE_MAPPING = ClassName.get("ru.gt2.gar.db.tm", "AbstractTableMapping");
    private static final ClassName TABLE_MAPPING = ClassName.get("ru.gt2.gar.db.tm", "TableMapping");
    private static final ClassName JDBC_TYPE = ClassName.get("java.sql", "JDBCType");
    private static final ClassName LOCAL_DATE = ClassName.get("java.time", "LocalDate");
    private static final ClassName SQL_EXCEPTION = ClassName.get("java.sql", "SQLException");
    private static final ClassName RESULT_SET = ClassName.get("java.sql", "ResultSet");
    private static final ClassName PREPARED_STATEMENT = ClassName.get("java.sql", "PreparedStatement");

    private final Path outputDir;

    static void main() throws IOException {
        Path output = Paths.get("gar-db", "src", "main", "java");
        new TableMappingGenerator(output).generate();
    }

    public void generate() throws IOException {
        DatabaseSchema schema = new DatabaseSchema(NamingStrategy.LOWER_UNDERSCORE);

        for (GarType garType : GarType.values()) {
            TypeSpec tmClass = generateTableMappingClass(garType, schema);
            JavaFile javaFile = JavaFile.builder("ru.gt2.gar.db.tm", tmClass)
                    .addFileComment("Generated by TableMappingGenerator")
                    .build();
            javaFile.writeTo(outputDir);
        }

        // Генерируем TableMappings (фабрику)
        TypeSpec mappingsClass = generateMappingsClass();
        JavaFile mappingsFile = JavaFile.builder("ru.gt2.gar.db.tm", mappingsClass)
                .addFileComment("Generated by TableMappingGenerator")
                .build();
        mappingsFile.writeTo(outputDir);
    }

    private TypeSpec generateTableMappingClass(GarType garType, DatabaseSchema schema) {
        String simpleName = garType.recordClass.getSimpleName();
        String className = simpleName + "TM";
        ClassName domainClass = ClassName.get(garType.recordClass);
        ClassName thisClass = ClassName.get("ru.gt2.gar.db.tm", className);

        QueriesGenerator queryGen = new QueriesGenerator(garType, schema);

        // SELECT
        String selectQuery = queryGen.getSelect();

        // INSERT
        String insertQuery = queryGen.getInsert();

        // Super constructor call
        CodeBlock superCall = CodeBlock.of("super($S, $L, $L, $L)",
                "INT",
                multiline(selectQuery),
                multiline(insertQuery),
                CodeBlock.of(simpleName + "::id"));

        TypeSpec.Builder classBuilder = TypeSpec.classBuilder(className)
                .superclass(ParameterizedTypeName.get(ABSTRACT_TABLE_MAPPING, domainClass, TypeName.INT))
                .addModifiers(Modifier.PUBLIC)
                .addJavadoc("Сгенерировано автоматически. Не редактировать.\n")
                .addMethod(MethodSpec.constructorBuilder()
                        .addStatement("super($N)", "superCall")
                        .addCode(superCall)
                        .build());

        // write(source, ps)
        MethodSpec writeMethod = generateWriteMethod(garType, domainClass, table);
        // read(rs)
        MethodSpec readMethod = generateReadMethod(garType, domainClass, table);

        return classBuilder
                .addMethod(writeMethod)
                .addMethod(readMethod)
                .build();
    }

    // TODO #9 Выделить генерацию методов записи и чтения в отдельные классы
    // которые implements TableVisitor для создания кода
    private MethodSpec generateWriteMethod(GarType garType, ClassName domainClass, DatabaseSchema.Table table) {
        return MethodSpec.methodBuilder("write")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .returns(void.class)
                .addParameter(domainClass, "source")
                .addParameter(PREPARED_STATEMENT, "ps")
                .addException(SQL_EXCEPTION)
                .addCode(generateWriteBody(table))
                .build();
    }

    private CodeBlock generateWriteBody(DatabaseSchema.Table table) {
        CodeBlock.Builder block = CodeBlock.builder();
        int index = 1;
        for (DatabaseSchema.Column col : table.columns) {
            String getter = "source." + col.propertyName + "()";
            if (col.type.equals("DATE")) {
                block.add("ps.setObject($L, $L, $T.$L);\n", index++, getter, JDBC_TYPE, "DATE");
            } else if (col.type.equals("BOOLEAN")) {
                block.add("ps.setBoolean($L, $L);\n", index++, getter);
            } else if (col.type.equals("INTEGER")) {
                block.add("ps.setInt($L, $L);\n", index++, getter);
            } else {
                block.add("ps.setString($L, $L);\n", index++, getter);
            }
        }
        return block.build();
    }

    private MethodSpec generateReadMethod(GarType garType, ClassName domainClass, DatabaseSchema.Table table) {
        MethodSpec.Builder method = MethodSpec.methodBuilder("read")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .returns(domainClass)
                .addParameter(RESULT_SET, "rs")
                .addException(SQL_EXCEPTION);

        CodeBlock.Builder block = CodeBlock.builder();
        block.add("$T id = rs.getInt(1);\n", int.class);

        int index = 2;
        for (DatabaseSchema.Column col : table.columns.subList(1, table.columns.size())) {
            String typeName;
            CodeBlock value;
            if (col.type.equals("DATE")) {
                typeName = "LocalDate";
                value = CodeBlock.of("rs.getObject($L, $T.class)", index++, LOCAL_DATE);
            } else if (col.type.equals("BOOLEAN")) {
                typeName = "boolean";
                value = CodeBlock.of("rs.getBoolean($L)", index++);
            } else if (col.type.equals("INTEGER")) {
                typeName = "int";
                value = CodeBlock.of("rs.getInt($L)", index++);
            } else {
                typeName = "String";
                value = CodeBlock.of("rs.getString($L)", index++);
            }
            block.add("$T $L = $L;\n", ClassName.get("java.lang", typeName), col.propertyName, value);
        }

        // Вызов конструктора record
        String args = table.columns.stream()
                .map(c -> c.propertyName)
                .collect(joining(", "));
        block.add("return new $T($L);\n", domainClass, args);

        method.addCode(block.build());
        return method.build();
    }

    private TypeSpec generateMappingsClass() {
        ClassName garType = ClassName.get(GarType.class);
        ClassName tableMapping = ParameterizedTypeName.get(TABLE_MAPPING,
                WildcardTypeName.supertypeOf(Object.class),
                WildcardTypeName.supertypeOf(Object.class));

        CodeBlock.Builder mapInit = CodeBlock.builder()
                .add("$T.<$T, $T>builder()\n", ImmutableMap.class, garType, tableMapping);

        for (GarType gt : GarType.values()) {
            String tmClassName = gt.getDomainClass().getSimpleName() + "TM";
            mapInit.add("    .put($T.$L, new $T())\n",
                    garType, gt.name(),
                    ClassName.get("ru.gt2.gar.db.tm", tmClassName));
        }

        mapInit.add("    .build();");

        FieldSpec mapField = FieldSpec.builder(
                        ParameterizedTypeName.get(ClassName.get(ImmutableMap.class), garType, tableMapping),
                        "MAP",
                        Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
                .initializer(mapInit.build())
                .build();

        MethodSpec getMethod = MethodSpec.methodBuilder("get")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(tableMapping)
                .addParameter(garType, "type")
                .addStatement("return MAP.get(type)")
                .build();

        return TypeSpec.classBuilder("TableMappings")
                .addModifiers(Modifier.PUBLIC)
                .addJavadoc("Фабрика TableMapping. Сгенерировано автоматически.\n")
                .addField(mapField)
                .addMethod(getMethod)
                .build();
    }

    private CodeBlock multiline(String sql) {
        return CodeBlock.of("\"\"\"\n                    $L\"\"\"", sql);
    }

}