package ru.gt2.gar.db.tm;

import com.google.common.collect.ImmutableMap;
import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.CodeBlock;
import com.palantir.javapoet.FieldSpec;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.ParameterizedTypeName;
import com.palantir.javapoet.TypeSpec;
import com.palantir.javapoet.WildcardTypeName;
import lombok.RequiredArgsConstructor;
import ru.gt2.gar.db.NamingStrategy;
import ru.gt2.gar.db.schema.DatabaseSchema;
import ru.gt2.gar.db.sql.QueriesGenerator;
import ru.gt2.gar.domain.GarType;

import javax.lang.model.element.Modifier;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;

@RequiredArgsConstructor
public class TableMappingGenerator {
    private static final ClassName ABSTRACT_TABLE_MAPPING = ClassName.get("ru.gt2.gar.db.tm", "AbstractTableMapping");
    private static final ClassName TABLE_MAPPING = ClassName.get("ru.gt2.gar.db.tm", "TableMapping");

    private final Path outputDir;

    static void main() throws IOException {
        Path output = Paths.get("gar-db", "src", "main", "java");
        new TableMappingGenerator(output).generate();
    }

    public void generate() throws IOException {
        DatabaseSchema schema = new DatabaseSchema(NamingStrategy.LOWER_UNDERSCORE);

        for (GarType garType : GarType.values()) {
            TypeSpec tmClass = generateTableMappingClass(garType, schema);
            JavaFile javaFile = JavaFile.builder("ru.gt2.gar.db.tm", tmClass)
                    .indent("    ")
                    .addFileComment("Generated by TableMappingGenerator")
                    .build();
            javaFile.writeTo(outputDir);
        }

        // Генерируем TableMappings (фабрику)
        TypeSpec mappingsClass = generateMappingsClass();
        JavaFile mappingsFile = JavaFile.builder("ru.gt2.gar.db.tm", mappingsClass)
                .indent("    ")
                .addFileComment("Generated by TableMappingGenerator")
                .build();
        mappingsFile.writeTo(outputDir);
    }

    private TypeSpec generateTableMappingClass(GarType garType, DatabaseSchema schema) {
        String simpleName = garType.recordClass.getSimpleName();
        String className = simpleName + "TM";
        ClassName domainClass = ClassName.get(garType.recordClass);

        QueriesGenerator queryGen = new QueriesGenerator(garType, schema);

        // SELECT
        String selectQuery = queryGen.getSelect();

        // INSERT
        String insertQuery = queryGen.getInsert();

        // Super constructor call
        CodeBlock superCall = CodeBlock.of("super($S, $L, $L,\n    $L)",
                "INT",
                multiline(selectQuery),
                multiline(insertQuery),
                CodeBlock.of(simpleName + "::id"));

        TypeSpec.Builder classBuilder = TypeSpec.classBuilder(className)
                .superclass(ParameterizedTypeName.get(ABSTRACT_TABLE_MAPPING, domainClass, ClassName.get(Integer.class)))
                .addModifiers(Modifier.PUBLIC)
                .addJavadoc("Сгенерировано автоматически. Не редактировать.\n")
                .addMethod(MethodSpec.constructorBuilder()
                        .addModifiers(Modifier.PUBLIC)
                        .addCode(superCall)
                        .build());

        MethodSpec writeMethod = generateWriteMethod(garType, schema);
        MethodSpec readMethod = generateReadMethod(garType, schema);

        return classBuilder
                .addMethod(writeMethod)
                .addMethod(readMethod)
                .build();
    }

    private MethodSpec generateWriteMethod(GarType garType, DatabaseSchema schema) {
        WriteMethodGenerator writerGen = new WriteMethodGenerator(garType.recordClass.getSimpleName());
        schema.visitTable(garType, writerGen); // предполагается, что Table implements Acceptable<TableVisitor>
        return writerGen.generate();
    }

    private MethodSpec generateReadMethod(GarType garType, DatabaseSchema schema) {
        ReadMethodGenerator readerGen = new ReadMethodGenerator(garType.recordClass.getSimpleName());
        schema.visitTable(garType, readerGen);
        return readerGen.generate();
    }

    private TypeSpec generateMappingsClass() {
        ClassName garType = ClassName.get(GarType.class);
        ParameterizedTypeName tableMapping = ParameterizedTypeName.get(TABLE_MAPPING,
                WildcardTypeName.supertypeOf(Object.class),
                WildcardTypeName.supertypeOf(Object.class));

        CodeBlock.Builder mapInit = CodeBlock.builder()
                .add("$T.<$T, $T>builder()\n", ImmutableMap.class, garType, tableMapping);

        for (GarType gt : GarType.values()) {
            String tmClassName = gt.recordClass.getSimpleName() + "TM";
            mapInit.add("    .put($T.$L, new $T())\n",
                    garType, gt.name(),
                    ClassName.get("ru.gt2.gar.db.tm", tmClassName));
        }

        mapInit.add("    .build();");

        FieldSpec mapField = FieldSpec.builder(
                        ParameterizedTypeName.get(ClassName.get(ImmutableMap.class), garType, tableMapping),
                        "MAP",
                        Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
                .initializer(mapInit.build())
                .build();

        MethodSpec getMethod = MethodSpec.methodBuilder("get")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(tableMapping)
                .addParameter(garType, "type")
                .addStatement("return MAP.get(type)")
                .build();

        return TypeSpec.classBuilder("TableMappings")
                .addModifiers(Modifier.PUBLIC)
                .addJavadoc("Фабрика TableMapping. Сгенерировано автоматически.\n")
                .addField(mapField)
                .addMethod(getMethod)
                .build();
    }

    private CodeBlock multiline(String sql) {
        return CodeBlock.of("\"\"\"\n    $L\"\"\"", sql);
    }

}