# Пример конфигурации
spring:
  datasource:
    url: jdbc:postgresql://localhost/gar
    username: gar
    password: some-gar-password
  # Тут видимо нужно определиться или мы включаем виртуальные потоки или просто пул на количество ядер
  task:
    execution:
      pool:
        core-size: 16
  threads:
    virtual:
      enabled: true
gar:
  xml:
    # Установка параметров jdk.xml.maxGeneralEntitySizeLimit и jdk.xml.totalEntitySizeLimit
    # Ибо начиная с java 24 появилось ограничение 100000, а как минимум для ГАР от 09.09.2025 нужно больше
    entitySizeLimit: 800000
  zip:
# архив полной версии
    full: C:/Tmp/2025-09-09_gar_xml.zip
