# Пример конфигурации
spring:
  datasource:
    url: jdbc:postgresql://localhost/gar
    username: gar
    password: some-gar-password
gar:
  zip:
# архив полной версии
    full: C:/Tmp/2025-09-09_gar_xml.zip
