
package ru.gt2.rusref.fias.update;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * Служба получения обновлений
 *
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.0
 *
 */
@WebServiceClient(name = "DownloadService", targetNamespace = "http://fias.nalog.ru/WebServices/Public/DownloadService.asmx/", wsdlLocation = "http://fias.nalog.ru/WebServices/Public/DownloadService.asmx?wsdl")
public class DownloadService
        extends Service
{

    private final static URL DOWNLOADSERVICE_WSDL_LOCATION;
    private final static WebServiceException DOWNLOADSERVICE_EXCEPTION;
    private final static QName DOWNLOADSERVICE_QNAME = new QName("http://fias.nalog.ru/WebServices/Public/DownloadService.asmx/", "DownloadService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://fias.nalog.ru/WebServices/Public/DownloadService.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DOWNLOADSERVICE_WSDL_LOCATION = url;
        DOWNLOADSERVICE_EXCEPTION = e;
    }

    public DownloadService() {
        super(__getWsdlLocation(), DOWNLOADSERVICE_QNAME);
    }

    public DownloadService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     *
     * @return
     *     returns DownloadServiceSoap
     */
    @WebEndpoint(name = "DownloadServiceSoap")
    public DownloadServiceSoap getDownloadServiceSoap() {
        return super.getPort(new QName("http://fias.nalog.ru/WebServices/Public/DownloadService.asmx/", "DownloadServiceSoap"), DownloadServiceSoap.class);
    }

    /**
     *
     * @return
     *     returns DownloadServiceSoap
     */
    @WebEndpoint(name = "DownloadServiceSoap12")
    public DownloadServiceSoap getDownloadServiceSoap12() {
        return super.getPort(new QName("http://fias.nalog.ru/WebServices/Public/DownloadService.asmx/", "DownloadServiceSoap12"), DownloadServiceSoap.class);
    }

    private static URL __getWsdlLocation() {
        if (DOWNLOADSERVICE_EXCEPTION!= null) {
            throw DOWNLOADSERVICE_EXCEPTION;
        }
        return DOWNLOADSERVICE_WSDL_LOCATION;
    }

}
