
package ru.gt2.rusref.fias.update;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.0
 *
 */
@WebService(name = "DownloadServiceSoap", targetNamespace = "http://fias.nalog.ru/WebServices/Public/DownloadService.asmx/")
public interface DownloadServiceSoap {


    /**
     * Возвращает информацию о последней версии файлов, доступных для скачивания
     *
     * @return
     *     returns ru.gt2.rusref.fias.update.DownloadFileInfo
     */
    @WebMethod(operationName = "GetLastDownloadFileInfo", action = "http://fias.nalog.ru/WebServices/Public/DownloadService.asmx/GetLastDownloadFileInfo")
    @WebResult(name = "GetLastDownloadFileInfoResult", targetNamespace = "http://fias.nalog.ru/WebServices/Public/DownloadService.asmx/")
    @RequestWrapper(localName = "GetLastDownloadFileInfo", targetNamespace = "http://fias.nalog.ru/WebServices/Public/DownloadService.asmx/", className = "ru.gt2.rusref.fias.update.GetLastDownloadFileInfo")
    @ResponseWrapper(localName = "GetLastDownloadFileInfoResponse", targetNamespace = "http://fias.nalog.ru/WebServices/Public/DownloadService.asmx/", className = "ru.gt2.rusref.fias.update.GetLastDownloadFileInfoResponse")
    public DownloadFileInfo getLastDownloadFileInfo();

    /**
     * Возвращает информацию о всех версиях файлов, доступных для скачивания
     *
     * @return
     *     returns ru.gt2.rusref.fias.update.ArrayOfDownloadFileInfo
     */
    @WebMethod(operationName = "GetAllDownloadFileInfo", action = "http://fias.nalog.ru/WebServices/Public/DownloadService.asmx/GetAllDownloadFileInfo")
    @WebResult(name = "GetAllDownloadFileInfoResult", targetNamespace = "http://fias.nalog.ru/WebServices/Public/DownloadService.asmx/")
    @RequestWrapper(localName = "GetAllDownloadFileInfo", targetNamespace = "http://fias.nalog.ru/WebServices/Public/DownloadService.asmx/", className = "ru.gt2.rusref.fias.update.GetAllDownloadFileInfo")
    @ResponseWrapper(localName = "GetAllDownloadFileInfoResponse", targetNamespace = "http://fias.nalog.ru/WebServices/Public/DownloadService.asmx/", className = "ru.gt2.rusref.fias.update.GetAllDownloadFileInfoResponse")
    public ArrayOfDownloadFileInfo getAllDownloadFileInfo();

}
