spring:
  application:
    name: dump-xml-stats

  # Настройки для цветного вывода в терминале
  output:
    ansi:
      enabled: always
gar:
  parse:
    # Размер пачки для потоковой обработки, по умолчанию — 1000
    batch: 1000